language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
# command to run tests
script:
  - PYTHONPATH=. pytest --cov=pystarling
after_success:
  - coveralls
